---
info:
  component: Default Single Swagger Document Server for MicroService

spring:
  profiles: default

server:
  port: 8014

documentation: 
  baseurl: http://localhost
  swagger: 
    services:   
      - 
        name: Service1
        url: ${documentation.baseurl}:8040/v2/api-docs?group=service1
        version: 2.0
      - 
        name: Service2
        url: ${documentation.baseurl}:8050/v2/api-docs?group=service2
        version: 2.0

 
    